import re

with open("index.html", "r", encoding="utf-8") as f:
    html = f.read()

# Replace the mangled formatReadableLog and the old recoverBackup with the clean correct version.

# I will use a regex to match from "const findQuestion = (id) => {" all the way to the end of the file,
# and replace it with the correct closing.

match_start = r"const findQuestion = \(id\) => \{"

correct_end = """const findQuestion = (id) => {
        for (let q of BANK.grammar) if (q.id === id) return q;
        for (let r of BANK.reading) {
          for (let q of r.questions) if (q.id === id) return q;
        }
        for (let q of BANK.writing) if (q.id === id) return q;
        for (let l of BANK.listening) {
          for (let q of l.questions) if (q.id === id) return q;
        }
        return null;
      };

      const appendSection = (title, questionIds) => {
        if (!questionIds || questionIds.length === 0) return;
        log += `\\n--- ${title} ---\\n`;
        questionIds.forEach((id, i) => {
          const q = findQuestion(id);
          const studentAns = (sub.answers[id] !== undefined && sub.answers[id] !== '') ? sub.answers[id] : '(no answer)';
          if (q) {
            let qText = q.text || q.prompt || '';
            let sAnsText = studentAns;
            if (q.type === 'mcq' && studentAns !== '(no answer)' && q.opts && q.opts[studentAns] !== undefined) {
              sAnsText = q.opts[studentAns];
            }
            log += `Q${i+1} [${q.id}]: ${qText}\\n`;
            log += `Response: ${sAnsText}\\n\\n`;
          } else {
            log += `Q [${id}]: Not found in bank\\n`;
            log += `Response: ${studentAns}\\n\\n`;
          }
        });
      };

      let readQs = [];
      if (sub.selectedQuestions.reading) {
        let r = BANK.reading.find(x => x.id === sub.selectedQuestions.reading);
        if (r && r.questions) readQs = r.questions.map(x => x.id);
      }
      
      let listQs = [];
      if (sub.selectedQuestions.listening) {
        let l = BANK.listening.find(x => x.id === sub.selectedQuestions.listening);
        if (l && l.questions) listQs = l.questions.map(x => x.id);
      }

      appendSection('GRAMMAR', sub.selectedQuestions.grammar);
      appendSection('LISTENING', listQs);
      appendSection('READING', readQs);
      appendSection('WRITING', sub.selectedQuestions.writing);

      return log.trim();
    }

    function handleBackupUpload(event) {
      const file = event.target.files[0];
      if (!file) return;
      const reader = new FileReader();
      reader.onload = function(e) {
        try {
          const text = e.target.result;
          let parsed;
          try {
            parsed = JSON.parse(text);
          } catch(err) {
            throw new Error("Invalid file format. Please upload a valid JSON backup file generated by the exam.");
          }
          
          let recoveredCount = 0;
          const items = Array.isArray(parsed) ? parsed : [parsed];
          
          items.forEach(item => {
            const id = item.id || item.db_id;
            const email = item.email || item.student_email;
            const date = item.date || item.exam_date;
            
            const exists = submissions.find(s => 
              (s.email === email && s.date === date) || 
              (s.id === id || s.db_id === id)
            );
            
            if (!exists) {
              const sub = {
                id: id || Date.now() + Math.random(),
                name: item.name || item.student_name,
                email: email,
                date: date,
                answers: item.answers,
                selectedQuestions: item.selectedQuestions || item.selected_questions,
                scores: item.scores,
                openPending: item.openPending || item.open_pending,
                graded: item.graded || false,
                emailSent: item.emailSent || item.email_sent || false,
                db_id: item.db_id || item.id
              };
              submissions.push(sub);
              recoveredCount++;
            }
          });

          if (recoveredCount > 0) {
            saveSubmissions();
            renderPanel();
            showModal('Recovery Successful', `${recoveredCount} exam(s) were successfully recovered and added to the panel.`, 'alert');
          } else {
            showModal('Recovery', 'All uploaded exams are already loaded in the panel. No new exams to recover.', 'alert');
          }
        } catch (err) {
          showModal('Error', err.message, 'alert');
        }
        event.target.value = ''; // reset input
      };
      reader.readAsText(file);
    }
  </script>
</body>
</html>"""

new_html = re.sub(match_start + r".*", correct_end, html, flags=re.DOTALL)

with open("index.html", "w", encoding="utf-8") as f:
    f.write(new_html)
